"""Added dates to forecasts

Revision ID: 9d86112894b0
Revises: 6478f1017de3
Create Date: 2024-08-08 16:31:52.474626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d86112894b0'
down_revision: Union[str, None] = '6478f1017de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forecast', sa.Column('dates', sa.String(length=511), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forecast', 'dates')
    # ### end Alembic commands ###
